// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyyclphbllaghivagtcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5eWNscGhibGxhZ2hpdmFndGNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjgwMjcsImV4cCI6MjA2ODg0NDAyN30.Jz0PV84R530CybM8o421PV1MoCNIe2fiYDtgL-FHPqM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});